# Start with a base image containing Java runtime
FROM ecar-turbo

# Make port 8080 available to the world outside this container
EXPOSE 8085

# The application's jar file
ARG JAR_FILE=acquisition/target/acquisition-1.0.0-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} acquisition.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/acquisition.jar"]