# Start with a base image containing Java runtime
FROM ecar-turbo

# Make port 8080 available to the world outside this container
EXPOSE 8083

# The application's jar file
ARG JAR_FILE=gateway/target/gateway-1.0.0-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} gateway.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/gateway.jar"]