server:
  port: 8083
  role: Gateway
  
management:
  endpoints:
    web.exposure:
      include: \*
  
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: acquisition
        uri: lb://acquisition
        predicates:
        - Path=/acquisition/**
        filters:
        - RewritePath=/acquisition/(?<segment>.*), /$\{segment}
      - id: distribution
        uri: lb://distribution
        predicates:
        - Path=/distribution/**
        filters:
        - RewritePath=/distribution/(?<segment>.*), /$\{segment}